#include "i2c_driver.h"

#include "stm32l0xx_hal.h"

// 1000 ms of timeout for all I2C transactions
#define TIMEOUT 1000U

void i2c_driver_init(I2C_HandleTypeDef *i2c, I2C_TypeDef *instance) {
    i2c->Instance = instance;
    i2c->Init.Timing =
        0x00100608;  // Based on 100KHz, rise of 400ns and fall of 100ns, Analog
                     // filter enabled. Generated by STM32CubeMX software
    i2c->Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    HAL_I2C_Init(i2c);

    HAL_I2CEx_ConfigAnalogFilter(i2c, I2C_ANALOGFILTER_ENABLE);
    HAL_I2CEx_ConfigDigitalFilter(i2c, 0);
}

void i2c_driver_scan(I2C_HandleTypeDef *i2c,
                     void (*user_handler)(uint8_t, void *),
                     void *user_handler_argument) {
    // NULL handler does nothing with the addresses so leave function
    if (user_handler == NULL) {
        return;
    }

    // Go upto max i2c address value of 127
    for (uint8_t address = 0; address < 128; address++) {
        // address << 1 for 7 bit addressing
        // check 10 times if the device is ready
        // 1000 ms of timeout
        uint32_t test = HAL_I2C_IsDeviceReady(i2c, address << 1, 10, TIMEOUT);

        // If sucessful, call handler to let the user process it
        if (test == HAL_OK) {
            user_handler(
                address,
                user_handler_argument);  // Pass in the address and their
                                         // argument to the handler
        }
    }
}

void i2c_driver_read_registers_with_stop(I2C_HandleTypeDef *i2c,
                                         uint8_t address, uint8_t *buffer,
                                         size_t numReceiveBytes) {
    // Send the transmit to tell which register to read from
    // Uses 1 byte from 'buffer' as the register value
    HAL_I2C_Master_Transmit(i2c, address << 1, buffer, 1, TIMEOUT);

    // Send receive to get the data back
    // Use the buffer again to receive into
    // numReceiveBytes of data to receive into the buffer
    HAL_I2C_Master_Receive(i2c, address << 1, buffer, numReceiveBytes, TIMEOUT);
}

void i2c_driver_write_registers(I2C_HandleTypeDef *i2c, uint8_t address,
                                uint8_t ireg, uint8_t *buffer,
                                size_t numBytes) {
    // Make the hal call based on a register being 1 byte long
    HAL_I2C_Mem_Write(i2c, address << 1, ireg, 1, buffer, numBytes, TIMEOUT);
}

void i2c_driver_read_registers(I2C_HandleTypeDef *i2c, uint8_t address,
                               uint8_t ireg, uint8_t *buffer, size_t numBytes) {
    // Make the hal call based on a register being 1 byte long
    HAL_I2C_Mem_Read(i2c, address << 1, ireg, 1, buffer, numBytes, TIMEOUT);
}
